metaborg/sdf

org.strategoxt.imp.editors.template/lib/ds/pp/Common-pp.str, org.strategoxt.imp.editors.template/lib/ds/pp/Module-pp.str, org.strategoxt.imp.editors.template/lib/ds/pp/Signatures-pp.str, org.strategoxt.imp.editors.template/lib/ds/pp/ds-pp.str, org.strategoxt.imp.editors.template/lib/ds/signatures/Signatures-sig.str, org.strategoxt.imp.editors.template/lib/ds/signatures/ds-sig.str, org.strategoxt.imp.editors.template/trans/generation/to-dynsem-sig.str
Extend the DynSem signature generator with the following:
1. generate correct syntax for nullary constructors
2. try to avoid duplicate sort declarations
3. generate implicit constructors from lexical declarations
4. generate implicit constructors from injections
Also updates the signature and pretty-printer to the latest available for DynSem.
=> Update DynSem signatures and extend signature generator

org.strategoxt.imp.editors.template/trans/editor/builders.str, org.strategoxt.imp.editors.template/trans/generation/to-dynsem-sig.str
This PR hooks the DynSem signature generator into the `generate-all` strategy. This means that DynSem signatures are generated during the build for each language.
=> Generate DynSem signature on-save

sdf2table.core/src/main/java/org/metaborg/sdf2table/io/Importer.java
Following your request, I have added it to the Importer.
CharClass(Simple(Absent())) is just ignored. I thing that's the easiest way to not destroy anything, but that only work if `Empty = []` has the same semantics as `Empty = `.
=> Add Absent character-cass to io.Importer

sdf2table.core/src/main/java/org/metaborg/sdf2table/core/CollisionSet.java, sdf2table.core/src/main/java/org/metaborg/sdf2table/io/Importer.java, sdf2table.core/src/main/java/org/metaborg/sdf2table/parsetable/Item.java, sdf2table.core/src/main/java/org/metaborg/sdf2table/parsetable/Lookahead.java, sdf2table.core/src/main/java/org/metaborg/sdf2table/parsetable/ParseTable.java, sdf2table.core/src/main/java/org/metaborg/sdf2table/parsetable/Reduce.java, sdf2table.core/src/main/java/org/metaborg/sdf2table/symbol/Alternative.java, sdf2table.core/src/main/java/org/metaborg/sdf2table/symbol/Followed.java, sdf2table.core/src/main/java/org/metaborg/sdf2table/symbol/Iteration.java, sdf2table.core/src/main/java/org/metaborg/sdf2table/symbol/Option.java, sdf2table.core/src/main/java/org/metaborg/sdf2table/symbol/Sequence.java, sdf2table.core/src/main/java/org/metaborg/sdf2table/symbol/SymbolCollection.java
I'm just considering the following things now:
- CollisionSet: We can try to get the agent of a null pointer (now it returns null).
- Importer: A symbol (`Absent`) can be imported as the null pointer. No need to request a unique pointer from the symbol collection then. null is null.
- SymbolCollection: The null pointer cannot be added to the collection.
=> Fix: NPE in importer bug

org.metaborg.meta.lang.template/editor/Menus.esv, org.metaborg.meta.lang.template/metaborg.yaml, org.metaborg.meta.lang.template/trans/editor/build-all.str, org.metaborg.meta.lang.template/trans/editor/build-sig.str, org.metaborg.meta.lang.template/trans/generation/signatures/to-scala-sig.str
There are known issues, but the Stratego code should be stable. It's in a separate builder, so it can only be called manually. 
Depends on publishing the spoofax-scala-interop library, which I'm opening another PR for to https://github.com/metaborg/mb-rep.
=> Scala case class generation

org.metaborg.meta.lang.template/trans/generation/signatures/to-scala-sig.str
Sorry for opening another PR, but @Gohla had me rename the library (so it's totally his fault 😛 ). Please wait for https://github.com/metaborg/mb-rep/pull/6 to be merged, in case there are more changes to the interop lib that require changes here.
=> Renamed lib once again

org.metaborg.sdf2table/src/main/java/org/metaborg/sdf2table/grammar/CharacterClass.java, org.metaborg.sdf2table/src/main/java/org/metaborg/sdf2table/grammar/CharacterClassConc.java, org.metaborg.sdf2table/src/main/java/org/metaborg/sdf2table/grammar/CharacterClassRange.java, org.metaborg.sdf2table/src/main/java/org/metaborg/sdf2table/grammar/IterSepSymbol.java, org.metaborg.sdf2table/src/main/java/org/metaborg/sdf2table/grammar/IterSymbol.java, org.metaborg.sdf2table/src/main/java/org/metaborg/sdf2table/grammar/OptionalSymbol.java
@udesou are you willing to merge these changes? This exposes the underlying symbol in the symbol classes. Some classes already had a `getSymbol` method, others were lacking access to their underlying symbol.
=> Make symbol in character class accessible

org.metaborg.sdf2table/src/main/java/org/metaborg/sdf2table/deepconflicts/DeepConflictsAnalyzer.java, org.metaborg.sdf2table/src/main/java/org/metaborg/sdf2table/parsetable/query/ProductionToGotoJavaHashMap.java
Just a tiny optimisation :slightly_smiling_face: 
- Used for-loop instead of stream in constructor of ProductionToGotoJavaHashMap
- Used `new HashSet<>(...)` instead of `....stream().collect(Collectors.toSet())` in DeepConflictsAnalyzer
=> Replace stream with loop / HashSet constructor

org.metaborg.parsetable/src/main/java/org/metaborg/parsetable/productions/ProductionReader.java, org.metaborg.parsetable/src/main/java/org/metaborg/parsetable/symbols/ISequenceSymbol.java, org.metaborg.parsetable/src/main/java/org/metaborg/parsetable/symbols/SequenceSymbol.java, org.metaborg.parsetable/src/main/java/org/metaborg/parsetable/symbols/SortCardinality.java, org.metaborg.parsetable/src/main/java/org/metaborg/parsetable/symbols/SymbolReader.java, org.metaborg.sdf2table/src/main/java/org/metaborg/sdf2table/grammar/SequenceSymbol.java
- The production attribute "deprecated" is now properly ignored (instead of throwing an exception when encountering it)
- Apparently, this attribute is used in (the parse table of) NaBL2. @jasperdenkers should it really be ignored or should this result in a warning somewhere?
- The order of SyntaxContext and SortCardinality no longer matters (e.g. both `cf(iter(...))` and `iter(cf(...))` are accepted now)
- The quick and dirty solution here is to check for the SyntaxContext again after checking for the SortCardinality.
- A sequence symbol is now properly read, including its subterms
- Note: apparently the GreenMarl parse table from the integration tests has `seq` represented with just a list (`seq([...])`) instead of using a `first` and `tail` (`seq(..., [...])`). I don't know why, but …
=> Fix three bugs in the parse table reader

org.metaborg.parsetable/src/main/java/org/metaborg/parsetable/characterclasses/CharacterClassOptimized.java, org.metaborg.parsetable/src/main/java/org/metaborg/parsetable/characterclasses/CharacterClassRangeSet.java
Apparently, empty character classes (in the form of `[]`) ended up in the parse table ATerm. The cause of this was a `CharacterClassRangeSet` that was empty, but did not get flagged as empty by the `isEmpty` method. In this particular case, the range set contained one range, namely `<47,48>` (note how both end points are _exclusive_), which still resulted in an empty character class.
Besides doing some refactoring, I've made sure that the `CharacterClassRangeSet.isEmpty` check actually checks whether the set is empty ([link](https://github.com/metaborg/sdf/pull/31/files#diff-d6390a0bdbcb54e65316fee87103f314L92-R82)).
=> Fix character classes

org.metaborg.parsetable/src/main/java/org/metaborg/parsetable/symbols/ISymbol.java
See metaborg/jsglr#57.
Calling `getSort` on a list/optional/etc symbol from a parse table taken directly from SDF3 generation used to return `null`, but calling `getSort` on the same sort of a serialized-and-deserialized parse table would return the base sort.
[The following code](https://github.com/metaborg/sdf/blob/cd53152dfd66440fcf17d431d2b5bc87ca04365d/org.metaborg.sdf2table/src/main/java/org/metaborg/sdf2table/grammar/Symbol.java#L110-L121) is used in the generated parse table to determine the sort:
```java
public static String getSort(ISymbol s) {
if(s instanceof Sort && ((Sort) s).getType() == null) {
return s.name();
} else if(s instanceof ContextFreeSymbol) {
return getSort(((ContextFreeSymbol) s).getSymbol());
} else if(s instanceof LexicalSymbol) {
return …
```
=> Let ISymbol.getSort only return a sort if it has no cardinality

org.metaborg.sdf2table/src/main/java/org/metaborg/sdf2table/io/NormGrammarReader.java
**The Problem:** In `NormGrammarReader.processSymbol`, a cache is maintained for symbols that are already processed. However, this cache did not take into account that Symbols with and without a Label should be treated as equal (e.g. `tail:Stm` and `Stm`, see [org.spoofax.jsglr2.integration/src/main/resources/grammars/layout-sensitive.sdf3](https://github.com/metaborg/jsglr/blob/develop/jsglr2/org.spoofax.jsglr2.integration/src/main/resources/grammars/layout-sensitive.sdf3)). These labels are only used to reference the symbols from the layout constraints, but do not actually contribute to the meaning of a production.
**Why is this a problem?** For SLR parse table generation (see #27), all grammar symbols are assumed to be unique. However, because Symbols with or without a Label were not …
=> Remove duplicate Symbols caused by a Label

org.metaborg.meta.lang.template/syntax/TemplateLang.sdf3, org.metaborg.meta.lang.template/trans/analysis/desugar.str
This pull request adds support for breaks in tokens that do not introduce layout in the template.
For example, this production:
ArrayType.ArrayType = <<ID>[]>
Can parse `a[]` but not `a[ ]`. If we want to allow layout in between the brackets, we have to write:
ArrayType.ArrayType = <<ID>[ ]>
Now it can parse both `a[]` and `a[ ]`, but pretty-printing will return `a[ ]`. If we don't want the space when pretty-printing, we can now insert a _non-layout token break_, written as `<>` (or equivalently `[]`):
ArrayType.ArrayType = <<ID>[<>]>
This still parses both `a[]` and `a[ ]`, but the pretty-printer will return `a[]`.
=> Non-layout token break support

org.metaborg.meta.lang.template/editor/Menus.esv, org.metaborg.meta.lang.template/trans/editor/build-misc.str, org.metaborg.meta.lang.template/trans/generation/textmate/gen-textmate-grammar.str, org.metaborg.meta.lang.template/trans/templatelang.str
TextMate grammars are supported for syntax highlighting in various editors, including VS Code, Atom, IntelliJ, Eclipse, and Theia. They use line-based Oniguruma regular expressions, but are very limited in the kinds of syntax highlighting they can express. While they do support recursive syntactic definitions, TextMate grammars are not powerful enough to perform sound highlighting for SGLR grammars.
This pull request adds to SDF3 a generator that can produce a rudimentary TextMate grammar for the language. The TextMate grammar performs syntax highlighting of the language's keywords and operators, and currently assumes C-style comments and string literals. Future work could include: expanding the TextMate grammar by performing heuristics on the SDF grammar; or, explicitly annotating the …
=> Add generator for rudimentary TextMate grammar

org.metaborg.parsetable/src/main/java/org/metaborg/parsetable/productions/Production.java, org.metaborg.parsetable/src/main/java/org/metaborg/parsetable/productions/ProductionReader.java
This inconsistency also caused differences in which parse nodes would be skippable in the parser, because `isSkippable` depends on `isLexical`.
=> Make isLexical of parsetable.ProductionReader consistent with sdf2table.ParseTableProduction

org.metaborg.parsetable/src/main/java/org/metaborg/parsetable/productions/IProduction.java, org.metaborg.parsetable/src/main/java/org/metaborg/parsetable/productions/Production.java, org.metaborg.parsetable/src/main/java/org/metaborg/parsetable/productions/ProductionReader.java, org.metaborg.sdf2table/src/main/java/org/metaborg/sdf2table/parsetable/ParseTableProduction.java
Note that we could also remove the method `isSkippableInParseForest()` entirely, but it makes more sense to use this method in the `Reducer`s where parse forests are skipped :slightly_smiling_face:
=> Mark everything that is not context-free as skippable in parse forest

org.metaborg.meta.lang.template/metaborg.yaml, org.metaborg.meta.lang.template/trans/editor/build-all.str, org.metaborg.meta.lang.template/trans/editor/build-completions.str, org.metaborg.meta.lang.template/trans/editor/build-deprecated.str, org.metaborg.meta.lang.template/trans/editor/build-format.str, org.metaborg.meta.lang.template/trans/editor/build-pp.str, org.metaborg.meta.lang.template/trans/editor/build-sdf-completions.str, org.metaborg.meta.lang.template/trans/editor/build-sig.str, org.metaborg.meta.lang.template/trans/editor/build-syntax.str, org.metaborg.meta.lang.template/trans/editor/build-utils.str, org.metaborg.meta.lang.template/trans/templatelang.str
Use the proper API for returning multiple files from the builder in SDF. This also improves the interaction with Statix and other languages that analyze generated files.
=> Return multiple files from builder, instead of writing files directly

org.metaborg.sdf2table/src/main/java/org/metaborg/sdf2table/parsetable/ParseTableProduction.java
This makes `ParseTableProduction.topDownHasSpaces(List<ISymbol>)` consistent with [`org.metaborg.parsetable.productions.ProductionReader`](https://github.com/metaborg/sdf/blob/master/org.metaborg.parsetable/src/main/java/org/metaborg/parsetable/productions/ProductionReader.java#L61-L90).
The ProductionReader reads an ATerm symbol from the parse table literally top-down: wrappers like `lex(...)`, `iter-star(...)`, etc. are stripped from the underlying character class.
This change in `ParseTableProduction` mimics this behaviour by stripping off the wrapper `Symbol` classes.
=> Consistent topDownHasSpaces between Java and ATerm parse table

org.metaborg.parsetable/src/main/java/org/metaborg/parsetable/IParseTableGenerator.java, org.metaborg.parsetable/src/main/java/org/metaborg/parsetable/productions/IProduction.java, org.metaborg.parsetable/src/main/java/org/metaborg/parsetable/productions/Production.java, org.metaborg.parsetable/src/main/java/org/metaborg/parsetable/productions/ProductionAttributes.java, org.metaborg.parsetable/src/main/java/org/metaborg/parsetable/productions/ProductionReader.java, org.metaborg.sdf2table/src/main/java/org/metaborg/sdf2table/deepconflicts/ContextualProduction.java, org.metaborg.sdf2table/src/main/java/org/metaborg/sdf2table/grammar/AssociativityInfo.java, org.metaborg.sdf2table/src/main/java/org/metaborg/sdf2table/grammar/NormGrammar.java, org.metaborg.sdf2table/src/main/java/org/metaborg/sdf2table/grammar/Production.java, org.metaborg.sdf2table/src/main/java/org/metaborg/sdf2table/io/NormGrammarReader.java, org.metaborg.sdf2table/src/main/java/org/metaborg/sdf2table/io/ParseTableIO.java, org.metaborg.sdf2table/src/main/java/org/metaborg/sdf2table/parsetable/ParseTable.java, org.metaborg.sdf2table/src/main/java/org/metaborg/sdf2table/parsetable/ParseTableProduction.java
To be merged together with metaborg/jsglr#86 and metaborg/spoofax#73. Recommended order of reading: SDF, JSGLR, Spoofax.
This PR starts with four minor refactoring commits, and after those, the fun stuff happens. :smile: 
Instead of globally keeping a list of pairs of mutually non-associative productions, each production now stores for itself in a `Set<Production>` which other productions it is non-associative with. This is done in [NormGrammarReader.java:858-866](https://github.com/metaborg/sdf/compare/master...mpsijm:non-assoc-warnings?expand=1#diff-26353ed93945b76e7df87914f87e6e79R858-R866).
When converting the grammar productions to parse table productions, for each production, their `Set<Production> nonAssocWith` is converted into a `Set<Integer>` representing the labels of the …
=> Errors for non-assoc by storing extra data in parse table

org.metaborg.meta.lang.template.test/layout-constraints/syntax.spt, org.metaborg.meta.lang.template/syntax/kernel/Kernel.sdf3, org.metaborg.meta.lang.template/syntax/layout-constraints/Layout-Constraints.sdf3, org.metaborg.meta.lang.template/syntax/sdf2-core/Sdf2.sdf3, org.metaborg.meta.lang.template/trans/analysis/desugar.str, org.metaborg.meta.lang.template/trans/analysis/name-constraints.str, org.metaborg.meta.lang.template/trans/generation/pp/to-pp.str, org.metaborg.sdf2table/src/main/java/org/metaborg/sdf2table/grammar/LayoutConstraintAttribute.java
In this PR I have created a new syntax for layout constraints. This new syntax aims at being simpler and easy to use. I have combined the `Constraint` and `ShortConstraint` into one `Constraint`, where low-level constraints and declarations can be used interchangeably. Furthermore, the position referencing in constraints now uses the same references as declarations, which means that it is possible to reference labels, but also positional indeces. This new syntax is also tested. Finally, I have removed some unused code and made the `all` constraint deprecated.
I have not made any changes to the analysis, except for some name changes to reflect the changes in syntax. The next step would be adding more error checking for invalid constraints. I haven't tested the generating of layout …
=> Feature: new layout constraint syntax

org.metaborg.sdf2table/src/main/java/org/metaborg/sdf2table/parsetable/State.java
Required for metaborg/jsglr#98.
I wanted to print the kernel of LR item sets in the logs, so I added a method that returns it.
While I was here anyway, I refactored the constructors, since they had much duplicate code.
=> Add method sdf2table.parsetable.State.getKernel()

org.metaborg.meta.lang.template/metaborg.yaml, org.metaborg.meta.lang.template/trans/editor/build-all.str, org.metaborg.meta.lang.template/trans/editor/build-syntax.str, org.metaborg.meta.lang.template/trans/generation/syntax/to-namespaced.str
PR required to be merged with or before this one: https://github.com/metaborg/spoofax/pull/82
Before this commit you would need to call a menu item manually to generate a namespaced grammar file. This was done because the generated file would be put into the `syntax` directory. Those were put there because the files needed to have the SDF3 on-save handler called on them as well.
With these changes, that menu is called on-save. The generated file will end up in `src-gen` instead of `syntax`. The `on-save` handler generates all other files for the namespaced grammar as it generates the namespaced grammar. 
Extra feature added: The namespaced grammar ends up in a subdirectory by the name of the language. This is to avoid module name clashes when mixing two namespaced grammars.
=> Auto generate namespaced grammar

org.metaborg.meta.lang.template/syntax/layout-constraints/Layout-Constraints.sdf3
In a previous PR of mine (#51) I deprecated the `all` layout constraint. However, I have done another thorough search and the constraint is not desugared or used in the parse table. So, syntax with this constraint does not even compile. Therefore, I suggest to remove it, since it is not used anywhere and the constraint used to be a hack to implement other layout declarations, which now have their own implementation. Please let me know if you know a place where it _is_ used.
=> Fix: remove all constraint

org.metaborg.meta.lang.template.test/layout-constraints/analysis.spt, org.metaborg.meta.lang.template/trans/analysis/desugar.str, org.metaborg.meta.lang.template/trans/analysis/name-constraints.str, org.metaborg.meta.lang.template/trans/generation/pp/to-pp.str
In this PR I have written analysis tests for layout constraints. I have added tests for the error checks that were already there, but also added tests and implementation for new errors and 1 new warning. The new checks include
* A warning for declaring a low level constraint without using any tree references.
* Applying `offside` to one terminal produces an error, since this can never parse.
* Add errors for applying `offside`, `indent`, `align` and `newline-indent` to the same tree. For example, when working with indices and labels and accidentally using a label with the same index.
* Add error for applying `offside` and `newline-indent` to arguments which come before the reference position in the production, since this would never parse.
Please let me know if any of these errors are …
=> Feature: layout constraints analysis tests

org.metaborg.meta.lang.template.test/layout-constraints/analysis-attributes.spt, org.metaborg.meta.lang.template.test/layout-constraints/analysis.spt, org.metaborg.meta.lang.template.test/layout-constraints/desugar.spt, org.metaborg.meta.lang.template/trans/analysis/desugar.str, org.metaborg.meta.lang.template/trans/analysis/name-constraints.str, org.metaborg.meta.lang.template/trans/templatelang.str
The desugaring of layout constraints had no tests, so I have written tests for many cases, cleaned up the code and fixed some corner cases.
* `AlignList` and pp constraints were not always correctly removed from constraints
* Added analysis to warn the user of incorrect use of `align-list`, since it can only be used inside `&&` and not `||` and `!`.
* Added analysis to warn the user when using multiple layouts for a single production or using `ignore-layout` as well as `layout`. Multiple layouts should be combined using `&&`
* Add retrieving quoted labels from productions
* Fix unlabeling symbols when getting them from productions
* Add retrieving single quoted literals from productions
* Fix  re-combining constraints in a left associative manner
* Split up redundant code into util …
=> Fix layout constraint desugar

org.metaborg.sdf2table/src/main/java/org/metaborg/sdf2table/grammar/layoutconstraints/BooleanLayoutConstraint.java
Fixed an issue where a boolean not constraint gave a `NullPointerException` when being normalized, since the second operand is `null` for not.
=> Fix: null pointer exception on Boolean constraint normalize

org.metaborg.parsetable/src/main/java/org/metaborg/parsetable/query/IProductionToGoto.java, org.metaborg.parsetable/src/main/java/org/metaborg/parsetable/query/ProductionToGotoForLoop.java, org.metaborg.parsetable/src/main/java/org/metaborg/parsetable/query/ProductionToGotoJavaHashMap.java, org.metaborg.parsetable/src/main/java/org/metaborg/parsetable/states/IState.java, org.metaborg.parsetable/src/main/java/org/metaborg/parsetable/states/State.java, org.metaborg.sdf2table/src/main/java/org/metaborg/sdf2table/parsetable/State.java
Required for metaborg/jsglr#100.
A change in the incremental parser requires retrieving the goto ID of any production on any state, even when the state does not have a goto for that production.
Note that this PR merges to `master`, and includes #56. The full Spoofax build succeeds on my machine™.
=> Add method State.getGotoId(int productionId, int devaultValue)

org.metaborg.meta.lang.template/trans/generation/signatures/to-sig.str
To be forward compatible with Stratego 2.
Only question is: does anything else depend on the current way of translating lexical syntax sorts to Stratego signatures?
=> Output string SortVar instead of String Sort for lexical syntax

org.metaborg.meta.lang.template.test/layout-constraints/analysis.spt, org.metaborg.meta.lang.template.test/layout-constraints/desugar.spt, org.metaborg.meta.lang.template.test/layout-constraints/syntax.spt, org.metaborg.meta.lang.template/syntax/layout-constraints/Layout-Constraints.sdf3, org.metaborg.meta.lang.template/trans/analysis/desugar.str, org.metaborg.meta.lang.template/trans/analysis/name-constraints.str
This PR adds a new `single-line` layout constraint, which can be used in 3 ways
1. `single-line` without arguments it will constrain the whole production to be on a single line
2. `single-line a` with one argument will constrain the given tree to be on a single line
3. `single-line a b` with two arguments will constrain both trees to be on the same line
The declaration is parsed with a list of arguments, but more than 2 are rejected in analysis, since writing `single-line a b c d` is the same as `single-line a d`. Furthermore, it cannot be applied to a single literal or multiple times to the same tree.
I have also added parse, analysis and desugar tests.
=> Feature: added layout constraint single-line
